# change the followings to match your Github username and repo name
baseurl: "/shroomagi.github.io" # the name of your github repo
url: "https://shroomagi.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Shroomagi - Security Research + OSRS"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Shroomagi
author-bio: Security Research + OSRS
 Content Coming Soon   # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/shroomagi
facebook: false
instagram: https://instagram.com/shroomagi
github: https://github.com/shroomagi
linkedin: false
medium: false
google-scholar: false
email: false
tiktok: https://tiktok.com/@shroomagi
twitch: https://twitch.com/shroomagi
youtube: https://www.youtube.com/@shroomagi
kick: https://kick.com/shroomagi
eth: https://app.ens.domains/shroomagi.eth
# footer information
footer-msg: "Shroomagi"
footer-msg-link: https://github.com/shroomagi

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
